### PR TITLE
Provide a build script

### PR DESCRIPTION
**Pull request by yeesian**

### CODE REVIEW

**Comment by visr** [comment]
Don't forget Homebrew for apple in the REQUIRE. And perhaps we should make libspatialindex_c the main alias, to prevent picking up the cpp shared library?

**Comment by yeesian** [comment]
> And perhaps we should make libspatialindex_c the main alias, to prevent picking up the cpp shared library?

Hm?

**Comment by visr** [comment]
I meant `library_dependency("spatialindex_c", aliases=["spatialindex_c-64"])`

In the downloaded Windows bin there are two shared libraries, `spatialindex_c-64.dll` and `spatialindex-64.dll`. Only the `_c` one exposes the desired C API right? Maybe I'm mistaken, what is the other one?

**Review by visr — APPROVED** [review]
Looks good!

**Pull request merged**
